[package]
name = "RustDortmundMeetupPage"
version = "0.1.0"
edition = "2021"
description = "Rust Dortmund Meetup Page using Yew and Trunk"
readme = "README.md"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
yew = { version="0.21", features=["csr"] }
yew-router = "0.18.0"
chrono = "0.4.41"
